### ISSUE TITLE
Support For CompactJsonFormatter and/or RenderedCompactJsonFormatter

### ISSUE THREAD

**Issue by bbrandt** [datalust/seq-import#6]
Is the seq-import tool able to natively import the output of CompactJsonFormatter and/or RenderedCompactJsonFormatter?  Or, would code changes be required for these formats to be passed through to Seq?

References:
https://github.com/serilog/serilog-formatting-compact
https://nblumhardt.com/2016/07/serilog-2-0-json-improvements/
datalust/seq-forwarder#12

**Comment by nblumhardt** [comment]
Hi Ben,

At the moment this would require a code change here. Once 3.3 is finalized I am keen to move on with datalust/seq-forwarder#12 to support the format over there, I don't think the seq-import version is likely to be updated in the short term, as the forwarder is going to become the "universal" client tool and covers the same functionality.

Hope this helps!
Nick

**Comment by bbrandt** [comment]
That's awesome.  I had wondered about that overlap of functionality.  Thanks for the update!
